sudo: required
services:
    - docker
    
before_install:
    - docker build -t shochats/docker-react -f Dockerfile.dev .
    
script:
    - docker run shochats/docker-react npm run test -- --coverage